version: "2"
run:
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - '**/*.go'
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: deprecated, should be replaced by standard lib errors package
    gocyclo:
      min-complexity: 15
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 5
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - wrapperFunc
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
    funlen:
      lines: 300
      statements: 200
  exclusions:
    paths:
      - .*_mock\.go$
      - swagger\/*
